name: "Droid Exec Base Action"
description: "Run Droid Exec in GitHub Actions workflows"
branding:
  icon: "code"
  color: "orange"

inputs:
  # Droid Exec arguments
  prompt:
    description: "The prompt to send to Droid Exec (mutually exclusive with prompt_file)"
    required: false
    default: ""
  prompt_file:
    description: "Path to a file containing the prompt to send to Droid Exec (mutually exclusive with prompt)"
    required: false
    default: ""
  settings:
    description: "Droid Exec settings as JSON string or path to settings JSON file"
    required: false
    default: ""

  reasoning_effort:
    description: "Optional reasoning effort to pass to Droid Exec via --reasoning-effort (e.g., 'low', 'medium', 'high', 'xhigh'). If empty, no --reasoning-effort flag is passed."
    required: false
    default: ""

  # Action settings
  droid_args:
    description: "Additional arguments to pass directly to Droid CLI (e.g., '--auto', '--enabled-tools read,edit')"
    required: false
    default: ""

  # Authentication settings
  factory_api_key:
    description: "Factory API key (required for Droid Exec invocations)"
    required: true
    default: ""

  use_node_cache:
    description: "Whether to use Node.js dependency caching (set to true only for Node.js projects with lock files)"
    required: false
    default: "false"
  path_to_droid_executable:
    description: "Optional path to a custom Droid CLI executable. If provided, skips automatic installation and uses this executable instead."
    required: false
    default: ""
  path_to_bun_executable:
    description: "Optional path to a custom Bun executable. If provided, skips automatic Bun installation and uses this executable instead. WARNING: Using an incompatible version may cause problems if the action requires specific Bun features. This input is typically not needed unless you're debugging something specific or have unique needs in your environment."
    required: false
    default: ""
  show_full_output:
    description: "Show full JSON output from Droid Exec. WARNING: This outputs ALL Droid messages including tool execution results which may contain secrets, API keys, or other sensitive information. These logs are publicly visible in GitHub Actions. Only enable for debugging in non-sensitive environments."
    required: false
    default: "false"

outputs:
  conclusion:
    description: "Execution status of Droid Exec ('success' or 'failure')"
    value: ${{ steps.run_droid.outputs.conclusion }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # https://github.com/actions/setup-node/releases/tag/v4.4.0
      with:
        node-version: ${{ env.NODE_VERSION || '18.x' }}
        cache: ${{ inputs.use_node_cache == 'true' && 'npm' || '' }}

    - name: Install Bun
      if: inputs.path_to_bun_executable == ''
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # https://github.com/oven-sh/setup-bun/releases/tag/v2.0.2
      with:
        bun-version: 1.2.11

    - name: Setup Custom Bun Path
      if: inputs.path_to_bun_executable != ''
      shell: bash
      run: |
        echo "Using custom Bun executable: ${{ inputs.path_to_bun_executable }}"
        # Add the directory containing the custom executable to PATH
        BUN_DIR=$(dirname "${{ inputs.path_to_bun_executable }}")
        echo "$BUN_DIR" >> "$GITHUB_PATH"

    - name: Install Dependencies
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        bun install

    - name: Install Droid CLI
      shell: bash
      run: |
        if [ -z "${{ inputs.path_to_droid_executable }}" ]; then
          echo "Installing Droid CLI..."
          curl --retry 5 --retry-delay 2 --retry-all-errors -fsSL https://app.factory.ai/cli | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          "$HOME/.local/bin/droid" --version
        else
          echo "Using custom Droid executable: ${{ inputs.path_to_droid_executable }}"
          DROID_DIR=$(dirname "${{ inputs.path_to_droid_executable }}")
          echo "$DROID_DIR" >> "$GITHUB_PATH"
        fi

    - name: Run Droid Exec Action
      shell: bash
      id: run_droid
      run: |
        # Change to DROID_WORKING_DIR if set (for running in custom directories)
        if [ -n "$DROID_WORKING_DIR" ]; then
          echo "Changing directory to DROID_WORKING_DIR: $DROID_WORKING_DIR"
          cd "$DROID_WORKING_DIR"
        fi
        bun run ${GITHUB_ACTION_PATH}/src/index.ts
      env:
        # Model configuration
        INPUT_PROMPT: ${{ inputs.prompt }}
        INPUT_PROMPT_FILE: ${{ inputs.prompt_file }}
        INPUT_SETTINGS: ${{ inputs.settings }}
        INPUT_DROID_ARGS: ${{ inputs.droid_args }}
        INPUT_REASONING_EFFORT: ${{ inputs.reasoning_effort }}
        INPUT_PATH_TO_DROID_EXECUTABLE: ${{ inputs.path_to_droid_executable }}
        INPUT_PATH_TO_BUN_EXECUTABLE: ${{ inputs.path_to_bun_executable }}
        INPUT_SHOW_FULL_OUTPUT: ${{ inputs.show_full_output }}

        # Provider configuration
        FACTORY_API_KEY: ${{ inputs.factory_api_key }}
