#!/usr/bin/env bun

/**
 * Prepare step for the GitLab `@droid fill` mode.
 *
 * Responsibilities:
 *   1. Parse GitLab CI env into a normalized context.
 *   2. Decide whether this pipeline should run fill, based on whether
 *      `@droid fill` appears in the MR title, description, or labels
 *      (or `automatic_fill` is enabled).
 *   3. Fetch the MR via API (description is not exposed as an env var)
 *      so we can match the trigger phrase against it.
 *   4. Write the fill prompt + a state file consumed by the CI script.
 *
 * Unlike the review flow this is a single-pass job: the fill prompt
 * itself calls `gitlab_mr___update_mr_description` to write back the
 * new description.
 */

import * as fs from "fs/promises";
import * as path from "path";
import { parseGitlabContext, isMergeRequestContext } from "../gitlab/context";
import { setupGitlabToken, MissingGitlabTokenError } from "../gitlab/token";
import { GitlabClient } from "../gitlab/api/client";
import { computeReviewArtifacts } from "../gitlab/data/review-artifacts";
import { checkContainsFillTrigger } from "../gitlab/validation/trigger";
import { generateGitlabFillPrompt } from "../gitlab/prompts/fill";
import { setupDroidSettings } from "../../base-action/src/setup-droid-settings";

export type FillPrepareState = {
  shouldRunFill: boolean;
  projectId: string;
  projectPath: string;
  mrIid: number | null;
  pipelineUrl: string | null;
  jobUrl: string | null;
  promptPath: string | null;
  fillModel: string | null;
  descriptionPath: string | null;
  diffPath: string | null;
  triggerSource: string;
  reason?: string;
};

function promptFilePath(): string {
  return process.env.DROID_PROMPT_FILE || "/tmp/droid-prompts/droid-prompt.txt";
}

function promptsDir(): string {
  return path.dirname(promptFilePath());
}

function stateFilePath(): string {
  return (
    process.env.DROID_STATE_FILE ||
    path.join(process.env.CI_PROJECT_DIR || "/tmp", ".droid-state.json")
  );
}

function resolvedEnvShimPath(): string {
  return (
    process.env.DROID_RESOLVED_ENV_FILE || "/tmp/droid-prompts/resolved-env.sh"
  );
}

function shellEscape(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

async function writeResolvedEnvShim(
  extras: Record<string, string | null>,
): Promise<void> {
  const filePath = resolvedEnvShimPath();
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  const lines = [
    "# Generated by gitlab-fill-prepare; source this to expose resolved env.",
  ];
  for (const [k, v] of Object.entries(extras)) {
    lines.push(`export ${k}=${shellEscape(v ?? "")}`);
  }
  await fs.writeFile(filePath, lines.join("\n") + "\n");
  console.log(`Wrote resolved env shim to ${filePath}`);
}

async function writeState(state: FillPrepareState): Promise<void> {
  const filePath = stateFilePath();
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, JSON.stringify(state, null, 2));
  console.log(`Wrote droid fill state to ${filePath}`);
}

async function run(): Promise<void> {
  const context = parseGitlabContext();

  const baseState: FillPrepareState = {
    shouldRunFill: false,
    projectId: context.project.id,
    projectPath: context.project.pathWithNamespace,
    mrIid: context.mr?.iid ?? null,
    pipelineUrl: context.pipelineUrl,
    jobUrl: context.jobUrl,
    promptPath: null,
    fillModel: context.inputs.fillModel || null,
    descriptionPath: null,
    diffPath: null,
    triggerSource: "none",
  };

  if (!isMergeRequestContext(context)) {
    console.log(
      "Not a merge_request_event pipeline; skipping droid fill prepare.",
    );
    await writeState({ ...baseState, reason: "not-merge-request-event" });
    return;
  }

  let token: string;
  try {
    token = setupGitlabToken();
  } catch (err) {
    if (err instanceof MissingGitlabTokenError) {
      console.error(err.message);
    }
    throw err;
  }

  try {
    await setupDroidSettings(context.inputs.settings || undefined);
  } catch (err) {
    console.warn(
      "Failed to setup droid settings; continuing with defaults:",
      err,
    );
  }

  const client = new GitlabClient(token, context.apiUrl);
  const mrIid = context.mr.iid;
  const projectId = context.project.id;

  // Description is not exposed as an env var; fetch via API.
  const mr = await client.getMr(projectId, mrIid);
  const description = mr.description ?? "";
  const title = mr.title ?? context.mr.title ?? "";
  const labels = context.mr.labels;

  const trigger = checkContainsFillTrigger({
    description,
    title,
    labels,
    triggerPhrase: context.inputs.triggerPhrase,
    automaticFill: context.inputs.automaticFill,
  });

  console.log(
    `Fill trigger check: matched=${trigger.matched} source=${trigger.source} ` +
      `triggerPhrase=${JSON.stringify(context.inputs.triggerPhrase)} ` +
      `labels=${JSON.stringify(labels)}`,
  );

  if (!trigger.matched) {
    console.log(
      "No fill trigger found in description/title/labels and automatic_fill is off; skipping droid exec.",
    );
    await writeState({
      ...baseState,
      reason: "no-fill-trigger",
      triggerSource: trigger.source,
    });
    return;
  }

  // Reuse the review-artifacts helper for diff + description; we ignore
  // existing_comments.json for fill mode (the prompt does not need them).
  console.log("Computing fill artifacts (diff, description)...");
  const artifacts = await computeReviewArtifacts({
    client,
    projectId,
    mrIid,
    outDir: promptsDir(),
  });
  console.log(
    `Artifacts written:\n  ${artifacts.diffPath}\n  ${artifacts.descriptionPath}`,
  );

  await writeResolvedEnvShim({
    DROID_MR_IID: String(mrIid),
    FILL_MODEL: context.inputs.fillModel || "",
  });

  const promptCtx = {
    projectPath: context.project.pathWithNamespace,
    mrIid,
    mrTitle: title,
    sourceBranch: artifacts.mr.source_branch ?? "",
    targetBranch: artifacts.mr.target_branch ?? "",
    triggerSource: trigger.source,
    triggerPhrase: context.inputs.triggerPhrase,
    descriptionPath: artifacts.descriptionPath,
    diffPath: artifacts.diffPath,
  };

  const prompt = generateGitlabFillPrompt(promptCtx);
  const promptPath = promptFilePath();
  await fs.mkdir(path.dirname(promptPath), { recursive: true });
  await fs.writeFile(promptPath, prompt);
  console.log(`Wrote fill prompt (${prompt.length} bytes) to ${promptPath}`);

  await writeState({
    ...baseState,
    shouldRunFill: true,
    promptPath,
    descriptionPath: artifacts.descriptionPath,
    diffPath: artifacts.diffPath,
    triggerSource: trigger.source,
  });
}

if (import.meta.main) {
  run().catch((error) => {
    console.error("gitlab-fill-prepare failed:", error);
    process.exit(1);
  });
}

export { run };
