name: "Droid Combine Results"
description: "Combine code review and security review results, post inline comments, update summary"

inputs:
  factory_api_key:
    description: "Factory API key"
    required: true
  tracking_comment_id:
    description: "ID of the tracking comment to update"
    required: true
  code_review_results:
    description: "Path to code review results JSON (optional)"
    required: false
    default: ""
  security_results:
    description: "Path to security results JSON (optional)"
    required: false
    default: ""
  code_review_status:
    description: "Code review job status (success/failure/skipped)"
    required: false
    default: "skipped"
  security_review_status:
    description: "Security review job status (success/failure/skipped)"
    required: false
    default: "skipped"

runs:
  using: "composite"
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76
      with:
        bun-version: 1.2.11

    - name: Install Dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}/..
        bun install
        cd ${{ github.action_path }}/../base-action
        bun install

    - name: Install Droid CLI
      shell: bash
      run: |
        curl --retry 5 --retry-delay 2 --retry-all-errors -fsSL https://app.factory.ai/cli | sh
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        "$HOME/.local/bin/droid" --version

    - name: Get GitHub Token
      id: token
      shell: bash
      run: |
        bun run ${{ github.action_path }}/../src/entrypoints/get-token.ts
      env:
        FACTORY_API_KEY: ${{ inputs.factory_api_key }}

    - name: Generate Combine Prompt
      id: prompt
      shell: bash
      run: |
        bun run ${{ github.action_path }}/../src/entrypoints/generate-combine-prompt.ts
      env:
        GITHUB_TOKEN: ${{ steps.token.outputs.github_token }}
        DROID_COMMENT_ID: ${{ inputs.tracking_comment_id }}
        CODE_REVIEW_RESULTS: ${{ inputs.code_review_results }}
        SECURITY_RESULTS: ${{ inputs.security_results }}
        CODE_REVIEW_STATUS: ${{ inputs.code_review_status }}
        SECURITY_REVIEW_STATUS: ${{ inputs.security_review_status }}

    - name: Run Combine
      shell: bash
      run: |
        bun run ${{ github.action_path }}/../base-action/src/index.ts
      env:
        INPUT_PROMPT_FILE: ${{ runner.temp }}/droid-prompts/droid-prompt.txt
        INPUT_DROID_ARGS: ${{ steps.prompt.outputs.droid_args }}
        INPUT_MCP_TOOLS: ${{ steps.prompt.outputs.mcp_tools }}
        FACTORY_API_KEY: ${{ inputs.factory_api_key }}
        GITHUB_TOKEN: ${{ steps.token.outputs.github_token }}
